### PR TITLE
Switches from identification to registration and add in_app option

### PR DESCRIPTION
**Pull request by danevron**

### CODE REVIEW

**Comment by danevron** [comment]
@yuval-netanel @tomerlevi444 @joaomilho - Please review this.
I basically added an option to send in_app=true and changed identification to registration.

**Comment by yuval-netanel** [comment]
:+1:

**Comment by grozen** [comment]
Would you mind explaining why this was necessary?
Please remember, this is the sample server referenced in all SDK documentations, so people should always know why it works the way it does with relative ease. I suspect `in_app` will be meaningless to outsiders (and I must admit I don't really grasp the need for it myself at the moment).

Also, please make sure the SDK documentations do not contain lies in light of these changes.

**Comment by yuval-netanel** [comment]
Guy, it's digital-goods sample server (not In-app) and none of our
customers are using this identification/registration

On Mon, Sep 7, 2015 at 12:29 AM, Guy Rozen <notifications@github.com> wrote:

> Would you mind explaining why this was necessary?
> Please remember, this is the sample server referenced in all SDK
> documentations, so people should always know why it works the way it does
> with relative ease. I suspect in_app will be meaningless to outsiders
> (and I must admit I don't really grasp the need for it myself at the
> moment).
>
> Also, please make sure the SDK documentations do not contain lies in light
> of these changes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/klarna/sample-digital-goods-backend/pull/9#issuecomment-138127477>
> .
>



-- 
Yuval Netanel
Software Developer
Engineering
+972 54 4956033
yuval.netanel@klarna.com <nadav.arbel@klarna.com>
klarna.com
Klarna
98 Yigal Alon st. Electra building. 13 floor.
Tel Aviv 67891 Israel

**Comment by grozen** [comment]
Ah, I assumed otherwise since I was getting notifications. Carry on, then!

**Comment by tomerlevi444** [comment]
Approved.

**Pull request merged**
