### PR TITLE
use od by env

### PR DESCRIPTION
**Pull request by eluxen**

### CODE REVIEW

**Comment by grozen** [comment]
I suspect there should be some documentation update to go along with this. No reason to keep all this goodness to yourself.

**Comment by joaomilho** [comment]
+1 @grozen , because if people wanna just test it, now they'll have to config the  ON_DEMAND_HOST env

**Comment by joaomilho** [comment]
[LGTM](http://lgtm.in/i/seAXj2noq)

**Comment by eluxen** [comment]
good catch!
fixed thanks.

**Pull request merged**
